In [1]:
from func_search import *
from func_def_class import *
from func_taux_transm import *
import os
from path import Path
import csv
#import matplotlib.pyplot as plt 
import ConfigParser
from struct import unpack
import re

In [2]:
from pandas import *
import pandas as pd
import sys
import matplotlib.pyplot as plt
from numpy import random

In [4]:
names = ['Bob','Jessica','Mary','John','Mel']
births = [968, 155, 77, 578, 973]

In [5]:
BabyDataSet = list(zip(names,births))
BabyDataSet

[('Bob', 968), ('Jessica', 155), ('Mary', 77), ('John', 578), ('Mel', 973)]

In [7]:
df = pd.DataFrame(data = BabyDataSet, columns=['Names', 'Births'])
df

     Names  Births
0      Bob     968
1  Jessica     155
2     Mary      77
3     John     578
4      Mel     973

In [8]:
df.dtypes

Names     object
Births     int64
dtype: object

In [10]:
# Method 1:
Sorted = df.sort_values(['Births'], ascending=False)
Sorted.head(2)

  Names  Births
4   Mel     973
0   Bob     968

In [15]:
random.seed(500)
random_names = [names[random.randint(low=0,high=len(names))] for i in range(1000)]

# Print first 10 records
random_names[:10]

['Mary',
 'Jessica',
 'Jessica',
 'Bob',
 'Jessica',
 'Jessica',
 'Jessica',
 'Mary',
 'Mary',
 'Mary']

In [17]:
# The number of births per name for the year 1880
births = [random.randint(low=0,high=1000) for i in range(1000)]
births[:10]

[905, 52, 796, 217, 874, 161, 605, 230, 593, 464]

In [18]:
BabyDataSet = list(zip(random_names,births))
BabyDataSet[:10]

[('Mary', 905),
 ('Jessica', 52),
 ('Jessica', 796),
 ('Bob', 217),
 ('Jessica', 874),
 ('Jessica', 161),
 ('Jessica', 605),
 ('Mary', 230),
 ('Mary', 593),
 ('Mary', 464)]

In [21]:
df = pd.DataFrame(data = BabyDataSet, columns=['Names', 'Births'])
df

       Names  Births
0       Mary     905
1    Jessica      52
2    Jessica     796
3        Bob     217
4    Jessica     874
5    Jessica     161
6    Jessica     605
7       Mary     230
8       Mary     593
9       Mary     464
10      John     444
11       Bob     392
12       Bob     576
13      Mary     563
14      Mary     130
15      John     823
16       Mel     419
17      Mary       6
18       Mel     641
19      John     559
20      John     182
21       Mel     240
22   Jessica     925
23      John     317
24   Jessica     348
25      Mary     191
26      Mary     836
27      John     524
28   Jessica     913
29       Bob     524
..       ...     ...
970  Jessica     720
971  Jessica     196
972  Jessica     152
973      Mel     203
974      Bob     583
975     John     466
976     Mary     839
977      Bob     113
978     John     544
979      Mel      55
980  Jessica     952
981     John     613
982     John     422
983      Mel     213
984     Mary     113
985      Mel      70
986      Mel     228
987  Jessica      62
988     John     487
989      Mel     245
990  Jessica     424
991     John     230
992      Bob     947
993      Mel      78
994  Jessica     487
995     John     875
996  Jessica     878
997     John      46
998  Jessica     657
999     John      87

[1000 rows x 2 columns]

In [23]:
df.to_csv('data_csv/births1880.csv',index=False,header=False)

In [75]:
df_tx = pd.read_csv(r'data_csv/pkt_tx.csv', dtype=str)
df_tx["asn"] = df_tx["asn"].astype(int)
df_tx

,time,addr,comp,asn,statType,trackinstance,trackowner,length,frameType,slotOffset,frequency,l2Dest,txpower,numTxAttempts,queuePos,succes_rx,succes_ack,list_rx
0,"2017-04-07 09:30:58,882",b868,22,730,3,0,0000000000000000,47,IEEE154_TYPE_DATA,121,16,ffffffffffffffff,31,1,0,0,0,NaN
1,"2017-04-07 09:31:07,538",b868,12,1015,3,0,0000000000000000,67,IEEE154_TYPE_BEACON,0,16,ffffffffffffffff,31,1,0,0,0,NaN
2,"2017-04-07 09:31:09,884",b868,22,1096,3,0,0000000000000000,47,IEEE154_TYPE_DATA,81,16,ffffffffffffffff,31,1,0,0,0,NaN
3,"2017-04-07 09:31:14,754",8772,15,1258,3,0,0000000000000000,61,IEEE154_TYPE_DATA,40,16,054332ff03dab868,31,1,0,0,0,NaN
4,"2017-04-07 09:31:14,754",b381,15,1258,3,0,0000000000000000,61,IEEE154_TYPE_DATA,40,16,054332ff03dab868,31,1,0,0,0,NaN
5,"2017-04-07 09:31:14,755",1162,12,1258,3,0,0000000000000000,67,IEEE154_TYPE_BEACON,40,16,ffff000000000000,31,1,1,0,0,NaN
6,"2017-04-07 09:31:15,477",1162,15,1282,3,0,0000000000000000,61,IEEE154_TYPE_DATA,81,16,054332ff03dab868,31,1,0,0,0,NaN
7,"2017-04-07 09:31:15,990",b381,15,1299,3,0,0000000000000000,61,IEEE154_TYPE_DATA,81,16,054332ff03dab868,31,2,0,0,0,NaN
8,"2017-04-07 09:31:17,191",8772,15,1339,3,0,0000000000000000,61,IEEE154_TYPE_DATA,121,16,054332ff03dab868,31,2,0,0,0,NaN
9,"2017-04-07 09:31:18,453",b381,22,1380,3,0,0000000000000000,47,IEEE154_TYPE_DATA,162,16,ffffffffffffffff,31,1,0,0,0,NaN
10,"2017-04-07 09:31:18,782",1162,22,1392,3,0,0000000000000000,47,IEEE154_TYPE_DATA,0,16,ffffffffffffffff,31,1,1,0,0,NaN
11,"2017-04-07 09:31:20,800",8772,12,1459,3,0,0000000000000000,67,IEEE154_TYPE_BEACON,40,16,ffff32ff03dab868,31,1,1,0,0,NaN
12,"2017-04-07 09:31:20,856",1162,15,1461,3,0,0000000000000000,61,IEEE154_TYPE_DATA,40,16,054332ff03dab868,31,2,0,0,0,NaN
13,"2017-04-07 09:31:20,858",b381,12,1461,3,0,0000000000000000,67,IEEE154_TYPE_BEACON,40,16,ffffffffffffffff,31,1,0,0,0,NaN
14,"2017-04-07 09:31:22,090",8772,22,1502,3,0,0000000000000000,47,IEEE154_TYPE_DATA,81,16,ffffffffffffffff,31,1,0,0,0,NaN
15,"2017-04-07 09:31:23,292",b868,15,1542,3,0,0000000000000000,52,IEEE154_TYPE_DATA,121,16,054332ff03d9b381,31,1,1,0,0,NaN
16,"2017-04-07 09:31:23,891",b868,15,1562,3,4,054332ff03dab868,52,IEEE154_TYPE_DATA,141,16,054332ff03da8772,31,1,2,0,0,NaN
17,"2017-04-07 09:31:24,525",b868,15,1583,3,0,0000000000000000,52,IEEE154_TYPE_DATA,162,16,054332ff03d9b381,31,2,1,0,0,NaN
18,"2017-04-07 09:31:25,846",b868,22,1624,3,0,0000000000000000,47,IEEE154_TYPE_DATA,0,16,ffffffffffffffff,31,1,0,0,0,NaN
19,"2017-04-07 09:31:26,959",c280,15,1664,3,0,0000000000000000,61,IEEE154_TYPE_DATA,40,16,054332ff03da8772,31,1,0,0,0,NaN
20,"2017-04-07 09:31:28,191",8772,15,1705,3,0,0000000000000000,52,IEEE154_TYPE_DATA,81,16,054332ff03d8c280,31,1,1,0,0,NaN
21,"2017-04-07 09:31:28,197",b381,22,1705,3,0,0000000000000000,47,IEEE154_TYPE_DATA,81,16,ffffffffffffffff,31,1,0,0,0,NaN
22,"2017-04-07 09:31:28,430",1162,22,1713,3,0,0000000000000000,47,IEEE154_TYPE_DATA,121,16,ffffffffffffffff,31,1,1,0,0,NaN
23,"2017-04-07 09:31:29,397",c280,22,1745,3,0,0000000000000000,47,IEEE154_TYPE_DATA,121,16,ffffffffffffffff,31,1,0,0,0,NaN
24,"2017-04-07 09:31:31,950",8772,22,1827,3,0,0000000000000000,47,IEEE154_TYPE_DATA,0,16,ffffffffffffffff,31,1,0,0,0,NaN
25,"2017-04-07 09:31:33,059",1162,15,1867,3,0,0000000000000000,61,IEEE154_TYPE_DATA,40,16,054332ff03dab868,31,3,0,0,0,NaN
26,"2017-04-07 09:31:33,060",b868,22,1867,3,0,0000000000000000,47,IEEE154_TYPE_DATA,40,16,ffffffffffffffff,31,1,0,0,0,NaN
27,"2017-04-07 09:31:33,061",c280,15,1867,3,0,0000000000000000,61,IEEE154_TYPE_DATA,40,16,054332ff03da8772,31,1,0,0,0,NaN
28,"2017-04-07 09:31:36,730",b381,22,1989,3,0,0000000000000000,47,IEEE154_TYPE_DATA,162,16,ffffffffffffffff,31,1,0,0,0,NaN
29,"2017-04-07 09:31:39,172",b868,12,2070,3,0,0000000000000000,67,IEEE154_TYPE_BEACON,40,16,ffff32ff03d9b381,31,1,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11503,"2017-04-07 12:49:35,242",8772,18,397173,3,3,054332ff03d8c280,110,IEEE154_TYPE_DATA,105,16,054332ff03dab868,31,1,0,0,0,NaN
11504,"2017-04-07 12:49:36,956",c280,22,397230,3,0,0000000000000000,47,IEEE154_TYPE_DATA,162,16,ffffffffffffffff,31,1,0,0,0,NaN
11505,"2017-04-07 12:49:41,824",b381,22,397392,3,0,0000000000000000,47,IEEE154_TYPE_DATA,121,16,ffffffffffffffff,31,1,0,0,0,NaN
11506,"2017-04-07 12:49:42,429",8772,22,397412,3,4,054332ff03dab868,111,IEEE154_TYPE_DATA,141,16,054332ff03dab868,31,1,0,0,0,NaN
11507,"2017-04-07 12:49:43,421",8772,27,397445,3,3,054332ff03da8772,110,IEEE154_TYPE_DATA,174,16,054332ff03dab868,31,1,1,0,0,NaN
11508,"2017-04-07 12:49:44,386",b381,12,397474,3,0,0000000000000000,67,IEEE154_TYPE_BEACON,0,16,ffff32ff03dab868,31,1,1,0,0,NaN
11509,"2017-04-07 12:49:44,389",1162,12,397474,3,0,0000000000000000,67,IEEE154_TYPE_BEACON,0,16,ffff32ff03d9b381,31,1,0,0,0,NaN
11510,"2017-04-07 12:49:44,413",8772,22,397474,3,0,0000000000000000,47,IEEE154_TYPE_DATA,0,16,ffffffffffffffff,31,1,0,0,0,NaN
11511,"2017-04-07 12:49:44,684",b381,27,397487,3,3,054332ff03d9b381,109,IEEE154_TYPE_DATA,13,16,054332ff03dab868,31,1,0,0,0,NaN
11512,"2017-04-07 12:49:45,493",1162,22,397514,3,0,0000000000000000,47,IEEE154_TYPE_DATA,40,16,ffffffffffffffff,31,1,0,0,0,NaN
11513,"2017-04-07 12:49:46,724",c280,22,397555,3,0,0000000000000000,47,IEEE154_TYPE_DATA,81,16,ffffffffffffffff,31,1,0,0,0,NaN
11514,"2017-04-07 12:49:50,481",b868,12,397677,3,0,0000000000000000,67,IEEE154_TYPE_BEACON,0,16,ffff32ff03d9b381,31,1,1,0,0,NaN
11515,"2017-04-07 12:49:51,592",c280,12,397717,3,0,0000000000000000,67,IEEE154_TYPE_BEACON,40,16,ffffffffffffffff,31,1,0,0,0,NaN
11516,"2017-04-07 12:49:51,593",b381,22,397717,3,0,0000000000000000,47,IEEE154_TYPE_DATA,40,16,ffffffffffffffff,31,1,0,0,0,NaN
11517,"2017-04-07 12:49:51,595",b868,0,397717,3,0,0000000000000000,0,IEEE154_TYPE_UNDEFINED,40,16,ffffffffffffffff,31,1,0,0,0,NaN
11518,"2017-04-07 12:49:52,255",1162,27,397739,3,3,054332ff02dc1162,110,IEEE154_TYPE_DATA,62,16,054332ff03da8772,31,1,0,0,0,NaN
11519,"2017-04-07 12:49:52,825",8772,12,397758,3,0,0000000000000000,67,IEEE154_TYPE_BEACON,81,16,ffff32ff03dab868,31,1,0,0,0,NaN
11520,"2017-04-07 12:49:53,188",c280,27,397770,3,3,054332ff03d8c280,110,IEEE154_TYPE_DATA,93,16,054332ff03da8772,31,1,0,0,0,NaN
11521,"2017-04-07 12:49:53,550",8772,18,397782,3,3,054332ff03d8c280,110,IEEE154_TYPE_DATA,105,16,054332ff03dab868,31,1,0,0,0,NaN
11522,"2017-04-07 12:49:54,028",1162,22,397798,3,0,0000000000000000,47,IEEE154_TYPE_DATA,121,16,ffffffffffffffff,31,1,0,0,0,NaN
11523,"2017-04-07 12:49:55,266",8772,22,397839,3,0,0000000000000000,47,IEEE154_TYPE_DATA,162,16,ffffffffffffffff,31,1,0,0,0,NaN
11524,"2017-04-07 12:49:56,826",8772,18,397891,3,3,054332ff02dc1162,110,IEEE154_TYPE_DATA,11,16,054332ff03dab868,31,1,1,0,0,NaN
11525,"2017-04-07 12:49:58,929",c280,22,397961,3,0,0000000000000000,47,IEEE154_TYPE_DATA,81,16,ffffffffffffffff,31,1,0,0,0,NaN
11526,"2017-04-07 12:50:00,131",b381,22,398001,3,0,0000000000000000,47,IEEE154_TYPE_DATA,121,16,ffffffffffffffff,31,1,0,0,0,NaN
11527,"2017-04-07 12:50:02,691",1162,22,398083,3,0,0000000000000000,47,IEEE154_TYPE_DATA,0,16,ffffffffffffffff,31,1,0,0,0,NaN
11528,"2017-04-07 12:50:03,948",c280,22,398128,3,4,054332ff03dab868,91,IEEE154_TYPE_DATA,45,16,054332ff03da8772,31,1,0,0,0,NaN
11529,"2017-04-07 12:50:05,031",8772,22,398164,3,0,0000000000000000,47,IEEE154_TYPE_DATA,81,16,ffffffffffffffff,31,1,1,0,0,NaN
11530,"2017-04-07 12:50:06,743",1162,22,398221,3,4,054332ff03dab868,91,IEEE154_TYPE_DATA,138,16,054332ff03da8772,31,1,0,0,0,NaN
11531,"2017-04-07 12:50:06,835",8772,18,398224,3,4,054332ff03dab868,91,IEEE154_TYPE_DATA,141,16,054332ff03dab868,31,1,1,0,0,NaN
11532,"2017-04-07 12:50:07,466",c280,22,398245,3,0,0000000000000000,47,IEEE154_TYPE_DATA,162,16,ffffffffffffffff,31,1,0,0,0,NaN

In [4]:
df_rx = pd.read_csv(r'data_csv/pkt_rx.csv', dtype=str)
df_rx["asn"] = df_rx["asn"].astype(int)
df_rx

,time,addr,comp,asn,statType,trackinstance,trackowner,length,frameType,slotOffset,frequency,l2Src,rssi,lqi,crc,queuePos,ACK_RX
0,"2017-04-07 09:31:07,577",8772,9,1015,4,0,0000000000000000,0,IEEE154_TYPE_BEACON,0,16,054332ff03dab868,189,125,1,0,0
1,"2017-04-07 09:31:07,577",b381,9,1015,4,0,0000000000000000,0,IEEE154_TYPE_BEACON,0,16,054332ff03dab868,188,51,1,0,0
2,"2017-04-07 09:31:07,578",1162,9,1015,4,0,0000000000000000,0,IEEE154_TYPE_BEACON,0,16,054332ff03dab868,188,238,1,0,0
3,"2017-04-07 09:31:07,582",c280,9,1015,4,0,0000000000000000,0,IEEE154_TYPE_BEACON,0,16,054332ff03dab868,165,215,1,0,0
4,"2017-04-07 09:31:09,884",b381,9,1096,4,0,0000000000000000,32,IEEE154_TYPE_DATA,81,16,054332ff03dab868,187,15,1,0,0
5,"2017-04-07 09:31:09,886",1162,9,1096,4,0,0000000000000000,32,IEEE154_TYPE_DATA,81,16,054332ff03dab868,189,15,1,0,0
6,"2017-04-07 09:31:09,886",8772,9,1096,4,0,0000000000000000,32,IEEE154_TYPE_DATA,81,16,054332ff03dab868,189,15,1,0,0
7,"2017-04-07 09:31:15,988",b868,9,1299,4,0,0000000000000000,38,IEEE154_TYPE_DATA,81,16,054332ff03d9b381,186,0,1,0,1
8,"2017-04-07 09:31:17,190",b868,9,1339,4,4,054332ff03dab868,38,IEEE154_TYPE_DATA,93,16,054332ff03da8772,188,0,1,0,1
9,"2017-04-07 09:31:18,424",1162,9,1380,4,0,0000000000000000,32,IEEE154_TYPE_DATA,162,16,054332ff03d9b381,178,0,1,2,0
10,"2017-04-07 09:31:22,088",b381,9,1502,4,0,0000000000000000,32,IEEE154_TYPE_DATA,81,16,054332ff03da8772,174,0,1,0,0
11,"2017-04-07 09:31:22,089",c280,9,1502,4,0,0000000000000000,32,IEEE154_TYPE_DATA,81,16,054332ff03da8772,195,9,1,0,0
12,"2017-04-07 09:31:23,894",8772,9,1562,4,0,0000000000000000,29,IEEE154_TYPE_DATA,162,16,054332ff03dab868,189,0,1,0,1
13,"2017-04-07 09:31:24,556",b381,9,1583,4,0,0000000000000000,29,IEEE154_TYPE_DATA,162,16,054332ff03dab868,186,0,1,0,1
14,"2017-04-07 09:31:26,958",8772,9,1664,4,0,0000000000000000,38,IEEE154_TYPE_DATA,40,16,054332ff03d8c280,195,0,1,0,1
15,"2017-04-07 09:31:28,190",c280,9,1705,4,0,0000000000000000,29,IEEE154_TYPE_DATA,81,16,054332ff03da8772,194,6,1,0,1
16,"2017-04-07 09:31:29,397",b868,9,1745,4,0,0000000000000000,32,IEEE154_TYPE_DATA,121,16,054332ff03d8c280,165,0,1,0,0
17,"2017-04-07 09:31:29,404",8772,9,1745,4,0,0000000000000000,32,IEEE154_TYPE_DATA,121,16,054332ff03d8c280,195,7,1,0,0
18,"2017-04-07 09:31:31,946",c280,9,1827,4,0,0000000000000000,32,IEEE154_TYPE_DATA,0,16,054332ff03da8772,195,0,1,0,0
19,"2017-04-07 09:31:31,948",b381,9,1827,4,0,0000000000000000,32,IEEE154_TYPE_DATA,0,16,054332ff03da8772,174,0,1,0,0
20,"2017-04-07 09:31:31,949",b868,9,1827,4,0,0000000000000000,32,IEEE154_TYPE_DATA,0,16,054332ff03da8772,189,0,1,1,0
21,"2017-04-07 09:31:33,061",8772,9,1867,4,0,0000000000000000,38,IEEE154_TYPE_DATA,40,16,054332ff03d8c280,195,0,1,0,1
22,"2017-04-07 09:31:36,725",1162,9,1989,4,0,0000000000000000,32,IEEE154_TYPE_DATA,162,16,054332ff03d9b381,178,0,1,2,0
23,"2017-04-07 09:31:36,727",b868,9,1989,4,0,0000000000000000,32,IEEE154_TYPE_DATA,162,16,054332ff03d9b381,186,0,1,0,0
24,"2017-04-07 09:31:39,162",b381,9,2070,4,0,0000000000000000,0,IEEE154_TYPE_BEACON,40,16,054332ff03dab868,186,51,1,1,0
25,"2017-04-07 09:31:39,166",1162,9,2070,4,0,0000000000000000,0,IEEE154_TYPE_BEACON,40,16,054332ff03dab868,189,238,1,3,0
26,"2017-04-07 09:31:40,754",b868,9,2123,4,4,054332ff03dab868,89,IEEE154_TYPE_DATA,93,16,054332ff03d9b381,186,203,1,0,1
27,"2017-04-07 09:31:42,199",b868,9,2171,4,4,054332ff03dab868,89,IEEE154_TYPE_DATA,141,16,054332ff03da8772,189,203,1,1,1
28,"2017-04-07 09:31:42,828",b381,9,2192,4,0,0000000000000000,32,IEEE154_TYPE_DATA,162,16,054332ff03dab868,187,0,1,0,0
29,"2017-04-07 09:31:44,152",c280,9,2233,4,0,0000000000000000,29,IEEE154_TYPE_DATA,0,16,054332ff03da8772,195,13,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17736,"2017-04-07 12:49:52,825",1162,9,397758,4,0,0000000000000000,0,IEEE154_TYPE_BEACON,81,16,054332ff03da8772,189,172,1,0,0
17737,"2017-04-07 12:49:52,827",b381,9,397758,4,0,0000000000000000,0,IEEE154_TYPE_BEACON,81,16,054332ff03da8772,174,128,1,0,0
17738,"2017-04-07 12:49:52,830",b868,9,397758,4,0,0000000000000000,0,IEEE154_TYPE_BEACON,81,16,054332ff03da8772,187,105,1,0,0
17739,"2017-04-07 12:49:53,189",8772,9,397770,4,3,054332ff03d8c280,89,IEEE154_TYPE_DATA,93,16,054332ff03d8c280,195,66,1,0,1
17740,"2017-04-07 12:49:53,549",b868,9,397782,4,3,054332ff03d8c280,89,IEEE154_TYPE_DATA,105,16,054332ff03da8772,188,37,1,0,1
17741,"2017-04-07 12:49:54,029",8772,9,397798,4,0,0000000000000000,32,IEEE154_TYPE_DATA,121,16,054332ff02dc1162,189,65,1,0,0
17742,"2017-04-07 12:49:54,030",b381,9,397798,4,0,0000000000000000,32,IEEE154_TYPE_DATA,121,16,054332ff02dc1162,183,15,1,0,0
17743,"2017-04-07 12:49:54,031",b868,9,397798,4,0,0000000000000000,32,IEEE154_TYPE_DATA,121,16,054332ff02dc1162,184,174,1,0,0
17744,"2017-04-07 12:49:55,259",1162,9,397839,4,0,0000000000000000,32,IEEE154_TYPE_DATA,162,16,054332ff03da8772,189,15,1,0,0
17745,"2017-04-07 12:49:55,263",b381,9,397839,4,0,0000000000000000,32,IEEE154_TYPE_DATA,162,16,054332ff03da8772,174,15,1,0,0
17746,"2017-04-07 12:49:55,265",c280,9,397839,4,0,0000000000000000,32,IEEE154_TYPE_DATA,162,16,054332ff03da8772,194,65,1,0,0
17747,"2017-04-07 12:49:55,271",b868,9,397839,4,0,0000000000000000,32,IEEE154_TYPE_DATA,162,16,054332ff03da8772,188,174,1,0,0
17748,"2017-04-07 12:49:56,825",b868,9,397891,4,3,054332ff02dc1162,89,IEEE154_TYPE_DATA,11,16,054332ff03da8772,188,37,1,0,1
17749,"2017-04-07 12:49:58,927",8772,9,397961,4,0,0000000000000000,32,IEEE154_TYPE_DATA,81,16,054332ff03d8c280,195,65,1,0,0
17750,"2017-04-07 12:49:58,929",b868,9,397961,4,0,0000000000000000,32,IEEE154_TYPE_DATA,81,16,054332ff03d8c280,165,202,1,0,0
17751,"2017-04-07 12:50:00,130",8772,9,398001,4,0,0000000000000000,32,IEEE154_TYPE_DATA,121,16,054332ff03d9b381,175,65,1,0,0
17752,"2017-04-07 12:50:00,132",1162,9,398001,4,0,0000000000000000,32,IEEE154_TYPE_DATA,121,16,054332ff03d9b381,183,15,1,0,0
17753,"2017-04-07 12:50:00,133",b868,9,398001,4,0,0000000000000000,32,IEEE154_TYPE_DATA,121,16,054332ff03d9b381,186,202,1,0,0
17754,"2017-04-07 12:50:02,685",b868,9,398083,4,0,0000000000000000,32,IEEE154_TYPE_DATA,0,16,054332ff02dc1162,184,202,1,1,0
17755,"2017-04-07 12:50:02,686",b381,9,398083,4,0,0000000000000000,32,IEEE154_TYPE_DATA,0,16,054332ff02dc1162,183,15,1,0,0
17756,"2017-04-07 12:50:02,715",8772,9,398083,4,0,0000000000000000,32,IEEE154_TYPE_DATA,0,16,054332ff02dc1162,189,65,1,0,0
17757,"2017-04-07 12:50:03,947",8772,9,398128,4,4,054332ff03dab868,70,IEEE154_TYPE_DATA,45,16,054332ff03d8c280,195,24,1,0,1
17758,"2017-04-07 12:50:05,028",b381,9,398164,4,0,0000000000000000,32,IEEE154_TYPE_DATA,81,16,054332ff03da8772,174,15,1,0,0
17759,"2017-04-07 12:50:05,029",1162,9,398164,4,0,0000000000000000,32,IEEE154_TYPE_DATA,81,16,054332ff03da8772,189,15,1,1,0
17760,"2017-04-07 12:50:05,031",c280,9,398164,4,0,0000000000000000,32,IEEE154_TYPE_DATA,81,16,054332ff03da8772,194,64,1,0,0
17761,"2017-04-07 12:50:05,032",b868,9,398164,4,0,0000000000000000,32,IEEE154_TYPE_DATA,81,16,054332ff03da8772,188,202,1,1,0
17762,"2017-04-07 12:50:06,743",8772,9,398221,4,4,054332ff03dab868,70,IEEE154_TYPE_DATA,138,16,054332ff02dc1162,189,24,1,1,1
17763,"2017-04-07 12:50:06,838",b868,9,398224,4,4,054332ff03dab868,70,IEEE154_TYPE_DATA,141,16,054332ff03da8772,188,25,1,1,1
17764,"2017-04-07 12:50:07,464",b868,9,398245,4,0,0000000000000000,32,IEEE154_TYPE_DATA,162,16,054332ff03d8c280,165,0,1,1,0
17765,"2017-04-07 12:50:07,469",8772,9,398245,4,0,0000000000000000,32,IEEE154_TYPE_DATA,162,16,054332ff03d8c280,195,64,1,1,0

In [319]:
print len(df2.loc[df2['asn']=="1015"])
df2.loc[(df2['asn']=="1015") & (df2['addr']=='8772')]
#for i in df2.loc[df2['asn']=='1015']:
 #   print "test"
    
if df2.loc[(df2['asn']=="1015") & (df2['addr']=='8772')]["asn"].str.endswith("5")[0]:
    print 'oui'

df_tx.dtypes
#.endswith("5")

#get_l2Src(line).endswith(addr_1)

4
oui

time             object
addr             object
comp             object
asn               int64
statType         object
trackinstance    object
trackowner       object
length           object
frameType        object
slotOffset       object
frequency        object
l2Dest           object
txpower          object
numTxAttempts    object
queuePos         object
succes_rx        object
succes_ack       object
dtype: object

In [92]:
df_tx.loc[ (df_tx['asn'] <= 1015) ]

,time,addr,comp,asn,statType,trackinstance,trackowner,length,frameType,slotOffset,frequency,l2Dest,txpower,numTxAttempts,queuePos,succes_rx,succes_ack,list_rx
0,"2017-04-07 09:30:58,882",b868,22,730,3,0,0000000000000000,47,IEEE154_TYPE_DATA,121,16,ffffffffffffffff,31,1,0,0,0,NaN
1,"2017-04-07 09:31:07,538",b868,12,1015,3,0,0000000000000000,67,IEEE154_TYPE_BEACON,0,16,ffffffffffffffff,31,1,0,0,0,NaN

4 ['8772', 'b381', '1162', 'c280']
[0, 1, 2, 3]
True
True
True
True